### ISSUE TITLE
Passing negative numbers to binder-call

### ISSUE THREAD

**Issue by litew** [mer-hybris/libgbinder#101]
Hello, 

I'm trying to emulate `adb wm overscan 0,0,0,0,-20` call but specifically addressed to aliendalvik (14 => number for [setOverscan](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android10-c2f2-release/core/java/android/view/IWindowManager.aidl#91) transaction for android.view.IWindowManager interface):
`binder-call -v -o -a -d /dev/puddlejumper window 14 '{ 0 0 0 0 4294967276 }'`
Here I'm using int32 overflow for passing negative number `-20`, and it works for some applications but not for all of them (seems like they filter out my input and don't allow integer overlow).

Is it possible to pass negative integer values as parameters when performing calls?

UPD: overflow number fix

**Comment by monich** [comment]
Makes sense

**Comment by litew** [comment]
@monich it works great now for all apps, thank you very much for implementing this feature.
