### ISSUE TITLE
Read string8 without a size

### ISSUE THREAD

**Issue by pszmynick** [mer-hybris/libgbinder#132]
Hi!
I'm struggling about one function. gbinder_reader_read_string8 reads a string byte by byte until the zero byte is reached. Is this a correct behavior? libbinder reads a size before that.
[link](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/binder/Parcel.cpp;drc=ff744535c8a7d9d658aea7ad6edf5a973f1b1e36;l=2269)

**Comment by monich** [comment]
`gbinder_reader_read_string8` seems to be the equivalent of `Parcel::readCString`. The naming is a bit confusing, I have to admit. What's the use case for `Parcel::readString8` (or `Parcel::writeString8`, for that matter)?

**Comment by pszmynick** [comment]
> `gbinder_reader_read_string8` seems to be the equivalent of `Parcel::readCString`. The naming is a bit confusing, I have to admit. What's the use case for `Parcel::readString8` (or `Parcel::writeString8`, for that matter)?

Oh, thank you, didn't assume that case. It is used for serializing some java classes in the framework. For example, CharSequence in [TextUtils.java](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/text/TextUtils.java#828)

**Comment by monich** [comment]
Would #134 make your life easier?

**Comment by pszmynick** [comment]
That's awesome. Thank you.
