### ISSUE TITLE
Not able to communicate with Android services in Android R using /dev/vndbinder and /dev/binder

### ISSUE THREAD

**Issue by ramalinga18680** [mer-hybris/libgbinder#50]
HI,

I am using libgbinder from a container to talk to the Android services.
When using this i am running into issues where it prints out the following log and does not do anything with binder-dump or binder-list when using both the binder device nodes, /dev/binder or /dev/vndbinder.

06-22 20:37:56.147   288   288 E Parcel  : Expecting header 0x564e4452 but found 0x6e0061. Mixing copies of libbinder?

06-22 20:39:01.898   285   285 E Parcel  : Expecting header 0x53595354 but found 0x6e0061. Mixing copies of libbinder?

06-22 20:47:48.875   288   288 E Parcel  : Expecting header 0x564e4452 but found 0x6e0061. Mixing copies of libbinder?

06-22 20:48:25.642   285   285 E Parcel  : Expecting header 0x53595354 but found 0x6e0061. Mixing copies of libbinder?

Please help.

[binder_container.log](https://github.com/mer-hybris/libgbinder/files/4815593/binder_container.log)

**Comment by monich** [comment]
Apparently google guys thought that it's a good idea to occasionally [break](https://android.googlesource.com/platform/frameworks/native/+/d70160f2989f18d4209ea464eb1635d4cc7ff827%5E%21/#F0) the protocol. libgbinder will have to somehow adapt to that. Which version of android are you using?

**Comment by ramalinga18680** [comment]
Hi,

I am using Android R and it seems to be working with these minor modifications in gbinder_rpc_protocol.c, but i am still testing.


const int32_t kVndHeader = B_PACK_CHARS('V', 'N', 'D', 'R');
const int32_t kSysHeader = B_PACK_CHARS('S', 'Y', 'S', 'T');
static const int32_t kUnsetWorkSource = -1;
static
void
gbinder_rpc_protocol_binder_write_rpc_header(
    GBinderWriter* writer,
    const char* iface,
    const char* dev)
{
    /*
     * writeInt32(IPCThreadState::self()->getStrictModePolicy() |
     *               STRICT_MODE_PENALTY_GATHER);
     * writeString16(interface);
     */
    gbinder_writer_append_int32(writer, BINDER_RPC_FLAGS);
    /*Add the work source uid and the rpc header before the iface */
    gbinder_writer_append_int32(writer, kUnsetWorkSource);
   if(dev && !strcmp(dev, GBINDER_DEFAULT_VNDBINDER))
    gbinder_writer_append_int32(writer, kVndHeader);
   else if(dev && !strcmp(dev, GBINDER_DEFAULT_BINDER))
    gbinder_writer_append_int32(writer, kSysHeader);
   gbinder_writer_append_string16(writer, iface);
}

static
const char*
gbinder_rpc_protocol_binder_read_rpc_header(
    GBinderReader* reader,
    guint32 txcode,
    char** iface)
{
    if (txcode > GBINDER_TRANSACTION(0,0,0)) {
        /* Internal transaction e.g. GBINDER_DUMP_TRANSACTION etc. */
        *iface = NULL;
    } else if (gbinder_reader_read_int32(reader, NULL)) {
        /* read out the work source uid and the rpc header */
        gbinder_reader_read_int32(reader, NULL);
        gbinder_reader_read_int32(reader, NULL);
        *iface = gbinder_reader_read_string16(reader);
    } else {
        *iface = NULL;
    }
    return *iface;
}

**Comment by ramalinga18680** [comment]
One more issue iam seeing with Android R is that the function gbinder_defaultservicemanager_list is not returning and is stuck in this while loop
    while ((reply = gbinder_client_transact_sync_reply(self->client,
        LIST_SERVICES_TRANSACTION, req, NULL)) != NULL)

Where the reply is never NULL and the same request is transmitted again and again and the same reply is received.
[test_vnd_binder.log](https://github.com/mer-hybris/libgbinder/files/4838075/test_vnd_binder.log)

Same issue with both the /dev/binder and /dev/vndbinder.

**Comment by monich** [comment]
Sounds like they changed servicemanager protocol too :/

**Comment by monich** [comment]
https://github.com/mer-hybris/libgbinder/pull/56 is the approach that I'm taking. It doesn't include all the known variants of protocols and service managers yet, but it establishes the framework for picking the right ones based on the configuration stored in a config file.

**Comment by JamiKettunen** [comment]
I believe at this point the issues were fixed [a long time ago](https://github.com/mer-hybris/libgbinder/commit/ab755054373c56cd82df0e29fde716001f11ba01)?

**Comment by monich** [comment]
Yes, I think so. Let's close this one.
